platform :ios, '13.0'

target 'FlashChat' do
  use_frameworks!
  inhibit_all_warnings! # add this and still getting warning from leveldb-library

  # Pods for FlashChat

  pod 'FirebaseAuth'
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '11.6.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end 
    end
  end

  target 'FlashChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlashChatUITests' do
    # Pods for testing
  end

end
