platform :ios, '17.0'

target 'FlashChat' do
  use_frameworks!

  # Pods for FlashChat

  target 'FlashChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlashChatUITests' do
    # Pods for testing
  end

end
